#!/bin/sh

### BEGIN INIT INFO
# Provides:          ntpd
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NTP daemon
# Description:       Network Time Protocol (NTP) is a networking
#                    protocol for clock synchronization
### END INIT INFO


DAEMON=/usr/sbin/ntpd
NAME=ntpd
DESC="Busybox NTP Daemon"
source /etc/ntp.conf
ARGS="-p $PEER"

test -f $DAEMON || exit 0

set -e

case "$1" in
    start)
        start-stop-daemon -S -b -n $NAME -a $DAEMON -- $ARGS
        echo "done."
        ;;
    stop)
        echo -n "stopping $DESC: $NAME... "
        start-stop-daemon -K -n $NAME
        echo "done."
        ;;
    restart)
        echo "restarting $DESC: $NAME... "
        $0 stop
        $0 start
        echo "done."
        ;;
    reload)
        echo -n "reloading $DESC: $NAME... "
        killall -HUP $(basename ${DAEMON})
        echo "done."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
        ;;
esac

exit 0
